<?php
namespace Database\Seeders;
use App\Models\{InterviewQuestion,InterviewSection};
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
class InterviewSeeder extends Seeder { public function run():void{$sections=[
'Modelo comercial'=>['¿Qué productos podrán contratarse mediante suscripción?','¿La suscripción tendrá descuento?','¿Cuál será el porcentaje o importe de descuento?','¿La primera compra tendrá un precio diferente?','¿Las renovaciones conservarán el precio inicial?','¿El precio podrá actualizarse?','¿Con cuánta anticipación se avisará un cambio de precio?','¿Habrá permanencia mínima?','¿Habrá una cantidad máxima por cliente?','¿Se permitirán códigos promocionales adicionales?'],
'Frecuencia'=>['¿El cobro será cada 30 días o por mes calendario?','¿El cliente podrá elegir la fecha?','¿Qué ocurre si el mes tiene menos días?','¿Se permitirán frecuencias distintas?','¿Se puede adelantar el próximo pedido?','¿Se puede omitir un ciclo?'],
'Pagos'=>['¿Qué proveedor se utilizará?','¿Mercado Pago será obligatorio o podrá existir otro proveedor?','¿Se cobrará inmediatamente al registrarse?','¿Cuándo debe crearse el pedido?','¿Qué estados de pago habilitan un pedido?','¿Cuántos reintentos se permitirán?','¿Qué ocurre después del último rechazo?','¿Quién atiende problemas de pago?','¿Se permitirá actualizar el medio de pago?','¿La suscripción se pausa automáticamente tras fallos?'],
'Pedidos y stock'=>['¿Debe reservarse stock para suscriptores?','¿Qué ocurre si no hay stock?','¿Se reemplaza por otro producto?','¿Se posterga el cobro?','¿Se devuelve el dinero?','¿Cuándo se descuenta inventario?','¿El pedido se crea automáticamente?','¿Tamara debe aprobar pedidos excepcionales?','¿Cómo se manejan productos discontinuados?'],
'Envío'=>['¿El envío está incluido?','¿El precio depende de la provincia?','¿Se admite todo el territorio argentino?','¿Qué transportistas se utilizarán?','¿Cómo se actualiza una dirección?','¿Hasta cuándo puede cambiarse antes del cobro?','¿Qué ocurre con una entrega fallida?','¿Quién absorbe una reexpedición?','¿Se permiten retiros?'],
'Cancelaciones'=>['¿El cliente puede cancelar cuando quiera?','¿Cuál es el plazo límite antes del siguiente cobro?','¿La cancelación es inmediata o al terminar el ciclo?','¿Puede pausarse en lugar de cancelar?','¿Puede reactivarse?','¿Debe indicarse un motivo?','¿Se requiere intervención humana?','¿Quién puede cancelar desde administración?'],
'Reembolsos'=>['¿Qué situaciones habilitan un reembolso?','¿Se devuelve también el envío?','¿Qué ocurre si el pedido ya fue despachado?','¿Cómo se tratan productos dañados?','¿Cómo se revierte la comisión del influencer?','¿Los reembolsos parciales están permitidos?'],
'IGS e influencers'=>['¿La comisión aplica solo a la primera compra?','¿Aplica también a renovaciones?','¿Durante cuántos ciclos?','¿La renovación conserva el influencer original?','¿Qué sucede si luego usa otro código?','¿Cuál es la base neta de comisión?','¿Se excluyen impuestos y envío?','¿Qué ocurre con devoluciones?','¿Qué porcentaje corresponde a cada nivel?','¿Hay excepciones por influencer?'],
'Legales y consentimiento'=>['¿Cuál será el texto exacto de autorización?','¿Cómo se informará el importe?','¿Cómo se informará la frecuencia?','¿Cómo se notificará el próximo cobro?','¿Cómo se notificará un cambio de precio?','¿Qué datos se conservarán?','¿Durante cuánto tiempo?','¿Quién es responsable del tratamiento?','¿Dónde podrá ejercer derechos el cliente?','¿Las políticas serán revisadas por un profesional legal?']];
$sectionPosition=0;foreach($sections as $name=>$questions){$section=InterviewSection::updateOrCreate(['slug'=>Str::slug($name)],['name'=>$name,'position'=>++$sectionPosition]);foreach($questions as $position=>$question)InterviewQuestion::firstOrCreate(['interview_section_id'=>$section->id,'question'=>$question],['explanation'=>'Definición necesaria para convertir la propuesta en una regla operativa.','why_it_matters'=>'Afecta la experiencia, los procesos o el cumplimiento de la suscripción.','answer_type'=>'textarea','status'=>'pending','impact'=>in_array($name,['Pagos','Legales y consentimiento'])?'critical':'high','responsible'=>'Tamara','position'=>$position+1]);}}
}
